version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db

  goapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
